### ISSUE TITLE
Question regarding reading practice feature

### ISSUE THREAD

**Issue by Pakkapao** [salemlf/hakubun#140]
Hello,
I'm Jakeipuu app developer. After taking a long break for almost 2 years, I decided to continue learning JP once again. Hakubun is my main app from now on! The UI is gorgeous!

I'm not sure if you are interested in integrating reading practice feature into Hakubun where articles are suggested based on user known vocabularies. The APIs seem to be still working fine after all these years. Please let me know your thought so that I can double check, make adjustment and share the details.

![image](https://github.com/salemlf/hakubun/assets/11070293/861483cb-a60e-409c-ac1b-1e2fc662ac19)

![image](https://github.com/salemlf/hakubun/assets/11070293/6ae155f5-fc4b-4ea6-bc99-9f8797889b6d)

**Comment by salemlf** [comment]
I would love to add reading practice, that'd be great! I've gotten questions before about adding that but hadn't been able to figure out what API(s) the data was pulled from. Thanks for the kind words! Jakeipuu was a big inspiration for Hakubun, I could tell a lot of thought went into it 😊

**Comment by Pakkapao** [comment]
The API was written by me and hosted with my own expense for this feature specifically. I'm afraid that I'm not going to maintain it anymore but I'm happy to keep it alive as long as it is working fine.

Here is an example. The API key is a demo one which only allow 80 requests per day.

```
curl --request POST \
  --url https://api.jakeipuu.com/article/search \
  --header 'Content-Type: application/json' \
  --header 'x-api-key: TxrhfeVRnf1d8Mnmgtghw3gauoNFV3deSNMcsLch' \
  --data '{
	"MinMatch": 0.2,
	"MaxMatch": 1,
	"Source": [
		"nhkeasy"
	],
	"KnownVocab": [
		"上げる",
		"上がる",
		"上る",
		"下がる",
		"下げる",
		"下さる",
		"入り口",
		"大きい",
		"大した",
		"大人",
		"千",
		"夕べ",
		"女の子",
		"子",
		"女子",
		"小さい",
		"丸い",
		"五月",
		"五つ",
		"六つ",
		"六月",
		"六",
		"円",
		"天",
		"天才",
		"手",
		"下手",
		"上手",
		"火山",
		"犬",
		"子犬",
		"王",
		"王子",
		"女王",
		"王女",
		"出す",
		"出る",
		"出口",
		"右",
		"右手",
		"左",
		"左手",
		"本",
		"日本",
		"正しい",
		"正す",
		"玉",
		"ビー玉",
		"玉ねぎ",
		"生まれる",
		"生む",
		"生きる",
		"白人",
		"目玉",
		"石",
		"立つ",
		"立てる",
		"万",
		"今",
		"今日",
		"今月",
		"元",
		"半分",
		"分かる",
		"分ける",
		"分",
		"切れる",
		"大切",
		"切る",
		"友人",
		"少ない",
		"引く",
		"心",
		"戸口",
		"止まる",
		"止める",
		"中止",
		"お父さん",
		"外人",
		"外れる"
	]
}'
```

**Comment by salemlf** [comment]
Ahh that makes sense, cool that you wrote it yourself! Do you have the API on GitHub? I'd be willing to fork it and maintain it if you're open to that! If not I'm also okay with using that API key and endpoint

**Comment by Pakkapao** [comment]
Yes, sure. I'm happy to push them to GitHub. Let's me find some free time to do it. It is not just code but also AWS resources.

That API is for demo anyway 😊. Can I send you the actual API Key to salemlfenn@gmail.com?

**Comment by salemlf** [comment]
Oh okay, panicking about the API key unnecessarily haha. Sounds good! Yep, that's my email, you can send it there 😊
