### ISSUE TITLE
Can't complete checkout of git error: invalid path 'src/images/cancel.svg:Zone.Identifier'

### ISSUE THREAD

**Issue by 00alia00** [salemlf/hakubun#218]
Tried to checkout the repository but it looks like that image breaks on windows, probably the ":"

error: invalid path 'src/images/cancel.svg:Zone.Identifier'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.

**Comment by 00alia00** [comment]
If anyone else gets here

```
git config core.protectNTFS false
git reset HEAD
```

gets you most of the way there :D leaves the offending file deleted locally

**Comment by salemlf** [comment]
Good to know! I've been using a Mac for months now, so probably why I hadn't noticed this
