### ISSUE TITLE
Assignments Setting - Sort by Last Update

### ISSUE THREAD

**Issue by salemlf** [salemlf/hakubun#224]
Add sorting option to sort by last update date, ascending or descending. 

- Should be under user settings page as an option for lesson and review sort order
- Should be under basic settings on both review and lesson setting pages

**Comment by DannyBrandt90** [comment]
I think I have successfully implemented this update, but ran into a bug when completing an assignment. I was unable to continue with lessons after submitting them. 

![image](https://github.com/salemlf/hakubun/assets/149819629/29867fb3-58e5-461e-b44f-c792a7888ca5)
