### ISSUE TITLE
Highlight On’yomi or Kun’yomi reading

### ISSUE THREAD

**Issue by Pakkapao** [salemlf/hakubun#290]
Hello,

I would like to propose to highlight either On’yomi or Kun’yomi reading based on Wanikani reading expectation. It is unclear which one is expected unless looking into Reading Mnemonic section. 

![image](https://github.com/salemlf/hakubun/assets/11070293/d0ff886f-5d1a-4532-9848-f8933f06d25c)

Example from Wanikani website:
![image](https://github.com/salemlf/hakubun/assets/11070293/862c311b-410c-448f-9219-6306ef491840)

I'm not sure if it is a good idea but probably **bold header** is easier to read than gray out.
![image](https://github.com/salemlf/hakubun/assets/11070293/5c33e473-114f-4102-8c95-4738b7a81dc4)

**Comment by salemlf** [comment]
That's a great idea! I agree that the greying out isn't the way to go, it's not accessible and there's better way to represent that. Bolding the text could work, or maybe a little checkmark icon next to on'yomi or kun'yomi?
