### ISSUE TITLE
An option to proceed with next item without swiping

### ISSUE THREAD

**Issue by Pakkapao** [salemlf/hakubun#303]
Hello,

I would like to propose for a setting to proceed with next review item automatically if answer is correct without swiping. I often typo and swipe to the right too quickly - just muscle memory :disappointed_relieved:. Also it helps speed up the review session a bit.

**Comment by salemlf** [comment]
This is a great idea! I'd been meaning to add something like it but forget to create a task 😅 I'll probably get to it sometime this week if someone else doesn't!
