### ISSUE TITLE
Reduce Swipe Animation time

### ISSUE THREAD

**Issue by EricosEagle** [salemlf/hakubun#356]
## Describe the Feature :rocket:

Currently the swipe animation takes a long time, and this really increases review times, especially if doing more than 20+ revieiws at a time. If the animation time will be reduced then reviews will be able to be done in a more efficient manner.

### Basic Example :paperclip:

See above

### Describe Alternatives You've Considered _(optional)_ :thinking:

Issue #331 can also solve this problem, as I assume an implementation of it will have a different animation or none at all.

### Additional Context :mag_right:

N/A

**Comment by salemlf** [comment]
This should be an easy fix! Has been on my to-do list for a while and keep forgetting about it
