### ISSUE TITLE
Artifact / Ghosting in reviews

### ISSUE THREAD

**Issue by EricosEagle** [salemlf/hakubun#364]
## Describe the Bug :bug:

First of all, thank you so much for working on this project, and closing 2 of my issues and adding them to the newest release! Unfortunately, it seems like it introduced a minor bug...

Now, every time a card is shown while reviewing (when it first shows up and when retrying after entering an incorrect answer), the information menu flashes on screen for a split second.
See the video below:
https://github.com/salemlf/hakubun/assets/36101457/72ae5c94-bda0-40b0-b5f3-eae858a3121a

### Steps to Reproduce :paw_prints:

Start reviewing

#### OS: (iOS, Android, etc.)
Android 14

#### App Version
2.5.3-beta

_This can be found at the bottom of the settings page_

**Comment by salemlf** [comment]
Oh ofc, you're welcome! I appreciate the details bug reports/feature requests. Ahhh yep I see the issue, it's an easy fix so should be updated within the day!
