### ISSUE TITLE
Light mode support?

### ISSUE THREAD

**Issue by lokesh-krishna** [salemlf/hakubun#39]
Thanks for this fantastic Android experience! Could you consider adding support for light mode?

**Comment by salemlf** [comment]
Thanks so much for the request! I originally planned on releasing the app with dark mode _and_ light mode, but got caught up in other things so it was put on the backburner. I can definitely add this though, likely will be done within the next month :)

**Comment by salemlf** [comment]
This is in progress now 😊

![localhost_5173_settings.png](https://github.com/salemlf/hakubun/assets/25971591/831ca040-cfa3-49d8-93a9-53e3a890505a)

**Comment by salemlf** [comment]
This has been added, update for Hakubun should be available either late tonight or early tomorrow! 🙂
