### ISSUE TITLE
Exception TypeError when doing reviews

### ISSUE THREAD

**Issue by ElReyZero** [salemlf/hakubun#53]
If you try to do vocabulary reviews answering any card correctly (be it either meaning or reading), the app throws an exception and doesn't let you advance. (Version 0.2.2-alpha)

![Screenshot_2023-11-03-05-42-02-87_7c879af1f5f1c2a492ce8d378096bd69.jpg](https://github.com/salemlf/hakubun/assets/31524106/4f0a5c91-7235-45c2-8c9c-3dd14c5b2cfe)

Review Settings:

![Screenshot_2023-11-03-05-46-53-18_7c879af1f5f1c2a492ce8d378096bd69.jpg](https://github.com/salemlf/hakubun/assets/31524106/f5f09edf-5785-495c-a589-c5107c10f123)

This happened any time I tried to do a vocabulary review, independent of which word I got. Kanji reviews worked fine.

**Comment by salemlf** [comment]
Oof oh no, that's a nasty bug! Looks like an easy fix though. Should be able to deploy a fix for that today, along with some testing to prevent that in future.

**Comment by salemlf** [comment]
Bug fix merged [here](https://github.com/salemlf/hakubun/pull/54), will put into review and hopefully fix will be available to download today 🙂
